CREATE TABLE `return_documents` (
  `id` CHAR(36) NOT NULL,
  `number` VARCHAR(191) NOT NULL,
  `type` ENUM('sale', 'purchase') NOT NULL,
  `source_document_id` CHAR(36) NOT NULL,
  `source_document_number` VARCHAR(191) NOT NULL,
  `journal_entry_id` CHAR(36) NOT NULL,
  `inventory_movement_id` CHAR(36) NOT NULL,
  `currency_code` ENUM('AFN', 'USD', 'PKR') NOT NULL,
  `subtotal` DECIMAL(18, 2) NOT NULL,
  `tax_total` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `total` DECIMAL(18, 2) NOT NULL,
  `refund_total` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `lines_snapshot` JSON NOT NULL,
  `notes` VARCHAR(191) NULL,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `return_documents_number_key` (`number`),
  UNIQUE INDEX `return_documents_journal_entry_id_key` (`journal_entry_id`),
  UNIQUE INDEX `return_documents_inventory_movement_id_key` (`inventory_movement_id`),
  INDEX `return_documents_type_source_document_id_idx` (`type`, `source_document_id`),
  INDEX `return_documents_created_at_idx` (`created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
